name: "REUSE Compliance workflow"

on:
  pull_request:
  push:

jobs:
  test-reuse-compliance:
    name: Test the commit for REUSE Compliance.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fsfe/reuse-action@v2
